sudo: required

services:
  - docker

os:
  - linux

language: python
python: 2.7

install:
  - docker version
  - python -V
  - pip list

script:
  - travis_wait 30 ./init.sh
  - travis_wait 10 . venv/bin/activate
  - travis_wait 45 fab build_rpms:gitea_version=1.3
