FROM centos:7


RUN yum clean all && \
    yum -y install \
      epel-release && \
    yum clean expire-cache && \
    yum -y install \
        @Development \
        fabric \
        python-jinja2 \
        python-pip \
        rpm-build \
        rpmdevtools


# Install test library
RUN pip install testinfra


RUN mkdir -p /builds && \
    rpmdev-setuptree


VOLUME [ "/builds" ]


COPY entrypoint.sh .


ENTRYPOINT ["/entrypoint.sh"]
